-- MySQL 구문
SELECT d.DEPT_ID
    , d.DEPT_NAME_EN
    , ROUND(AVG(e.SAL), 0) AS AVG_SAL
FROM HR_DEPARTMENT d, HR_EMPLOYEES e
WHERE d.DEPT_ID = e.DEPT_ID
GROUP BY d.DEPT_ID
ORDER BY 3 DESC;

-- ANSI SQL 구문
SELECT d.DEPT_ID
    , d.DEPT_NAME_EN
    , ROUND(AVG(e.SAL), 0) AS AVG_SAL
FROM HR_DEPARTMENT d
    JOIN HR_EMPLOYEES e ON d.DEPT_ID = e.DEPT_ID
GROUP BY d.DEPT_ID
ORDER BY 3 DESC;