-- MySQL
SELECT b.BOOK_ID
    , a.AUTHOR_NAME
    , DATE_FORMAT(b.PUBLISHED_DATE, '%Y-%m-%d')
FROM BOOK b, AUTHOR a
WHERE b.AUTHOR_ID = a.AUTHOR_ID
    AND b.CATEGORY = '경제'
ORDER BY 3;

-- ANSI
SELECT b.BOOK_ID
   , a.AUTHOR_NAME
   , DATE_FORMAT(b.PUBLISHED_DATE, '%Y-%m-%d')
FROM BOOK b JOIN AUTHOR a
    ON b.,AUTHOR_ID = a.AUTHOR_ID
WHERE b.CATEGORY = '경제'
ORDER BY 3;