-- MySQl
SELECT DISTINCT(h.CAR_ID)
FROM CAR_RENTAL_COMPANY_CAR c, CAR_RENTAL_COMPANY_RENTAL_HISTORY h
WHERE c.CAR_ID = h.CAR_ID
    AND MONTH(h.START_DATE) = '10'
    AND c.CAR_TYPE = '세단'
ORDER BY 1 DESC;

-- ANSI
SELECT DISTINCT(h.CAR_ID)
FROM CAR_RENTAL_COMPANY_CAR c
    INNER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY h
        ON c.CAR_ID = h.CAR_ID
WHERE MONTH(h.START_DATE) = '10'
    AND c.CAR_TYPE = '세단'
ORDER BY 1 DESC;